var annotated_dup =
[
    [ "cgs", "namespacecgs.html", [
      [ "ecs", "namespacecgs_1_1ecs.html", [
        [ "ComponentStorage", "classcgs_1_1ecs_1_1ComponentStorage.html", "classcgs_1_1ecs_1_1ComponentStorage" ],
        [ "ComponentType", "structcgs_1_1ecs_1_1ComponentType.html", null ],
        [ "Entity", "structcgs_1_1ecs_1_1Entity.html", "structcgs_1_1ecs_1_1Entity" ],
        [ "EntityManager", "classcgs_1_1ecs_1_1EntityManager.html", "classcgs_1_1ecs_1_1EntityManager" ],
        [ "IComponentStorage", "classcgs_1_1ecs_1_1IComponentStorage.html", "classcgs_1_1ecs_1_1IComponentStorage" ],
        [ "ISystem", "classcgs_1_1ecs_1_1ISystem.html", "classcgs_1_1ecs_1_1ISystem" ],
        [ "Query", "classcgs_1_1ecs_1_1Query.html", "classcgs_1_1ecs_1_1Query" ],
        [ "Read", "structcgs_1_1ecs_1_1Read.html", null ],
        [ "ScratchAllocator", "classcgs_1_1ecs_1_1ScratchAllocator.html", "classcgs_1_1ecs_1_1ScratchAllocator" ],
        [ "SystemAccessInfo", "structcgs_1_1ecs_1_1SystemAccessInfo.html", "structcgs_1_1ecs_1_1SystemAccessInfo" ],
        [ "SystemScheduler", "classcgs_1_1ecs_1_1SystemScheduler.html", "classcgs_1_1ecs_1_1SystemScheduler" ],
        [ "SystemType", "structcgs_1_1ecs_1_1SystemType.html", null ],
        [ "Write", "structcgs_1_1ecs_1_1Write.html", null ]
      ] ],
      [ "foundation", "namespacecgs_1_1foundation.html", [
        [ "detail", "namespacecgs_1_1foundation_1_1detail.html", [
          [ "BinaryReader", "structcgs_1_1foundation_1_1detail_1_1BinaryReader.html", "structcgs_1_1foundation_1_1detail_1_1BinaryReader" ],
          [ "is_serializable", "structcgs_1_1foundation_1_1detail_1_1is__serializable.html", null ],
          [ "is_serializable< T, std::void_t< decltype(SerializableTraits< T >::schema_version)> >", "structcgs_1_1foundation_1_1detail_1_1is__serializable_3_01T_00_01std_1_1void__t_3_01decltype_07Sac1188e26c006f2f00b19e3dfbc7ec84.html", null ],
          [ "JsonReader", "structcgs_1_1foundation_1_1detail_1_1JsonReader.html", "structcgs_1_1foundation_1_1detail_1_1JsonReader" ]
        ] ],
        [ "ConfigManager", "classcgs_1_1foundation_1_1ConfigManager.html", "classcgs_1_1foundation_1_1ConfigManager" ],
        [ "CorrelationScope", "classcgs_1_1foundation_1_1CorrelationScope.html", "classcgs_1_1foundation_1_1CorrelationScope" ],
        [ "DatabaseConfig", "structcgs_1_1foundation_1_1DatabaseConfig.html", "structcgs_1_1foundation_1_1DatabaseConfig" ],
        [ "DbNull", "structcgs_1_1foundation_1_1DbNull.html", null ],
        [ "EntityIdTag", "structcgs_1_1foundation_1_1EntityIdTag.html", null ],
        [ "FieldDescriptor", "structcgs_1_1foundation_1_1FieldDescriptor.html", "structcgs_1_1foundation_1_1FieldDescriptor" ],
        [ "GameDatabase", "classcgs_1_1foundation_1_1GameDatabase.html", "classcgs_1_1foundation_1_1GameDatabase" ],
        [ "GameError", "classcgs_1_1foundation_1_1GameError.html", "classcgs_1_1foundation_1_1GameError" ],
        [ "GameJobScheduler", "classcgs_1_1foundation_1_1GameJobScheduler.html", "classcgs_1_1foundation_1_1GameJobScheduler" ],
        [ "GameLogger", "classcgs_1_1foundation_1_1GameLogger.html", "classcgs_1_1foundation_1_1GameLogger" ],
        [ "GameMetrics", "classcgs_1_1foundation_1_1GameMetrics.html", "classcgs_1_1foundation_1_1GameMetrics" ],
        [ "GameNetworkManager", "classcgs_1_1foundation_1_1GameNetworkManager.html", "classcgs_1_1foundation_1_1GameNetworkManager" ],
        [ "GameSerializer", "classcgs_1_1foundation_1_1GameSerializer.html", "classcgs_1_1foundation_1_1GameSerializer" ],
        [ "HealthCheckResult", "structcgs_1_1foundation_1_1HealthCheckResult.html", "structcgs_1_1foundation_1_1HealthCheckResult" ],
        [ "HistogramBuckets", "structcgs_1_1foundation_1_1HistogramBuckets.html", "structcgs_1_1foundation_1_1HistogramBuckets" ],
        [ "JsonLogFormatter", "classcgs_1_1foundation_1_1JsonLogFormatter.html", null ],
        [ "LogContext", "structcgs_1_1foundation_1_1LogContext.html", "structcgs_1_1foundation_1_1LogContext" ],
        [ "NetworkMessage", "structcgs_1_1foundation_1_1NetworkMessage.html", "structcgs_1_1foundation_1_1NetworkMessage" ],
        [ "PlayerIdTag", "structcgs_1_1foundation_1_1PlayerIdTag.html", null ],
        [ "PreparedStatement", "classcgs_1_1foundation_1_1PreparedStatement.html", "classcgs_1_1foundation_1_1PreparedStatement" ],
        [ "SerializableTraits", "structcgs_1_1foundation_1_1SerializableTraits.html", null ],
        [ "ServiceLocator", "classcgs_1_1foundation_1_1ServiceLocator.html", "classcgs_1_1foundation_1_1ServiceLocator" ],
        [ "SessionIdTag", "structcgs_1_1foundation_1_1SessionIdTag.html", null ],
        [ "SessionInfo", "structcgs_1_1foundation_1_1SessionInfo.html", "structcgs_1_1foundation_1_1SessionInfo" ],
        [ "Signal", "classcgs_1_1foundation_1_1Signal.html", "classcgs_1_1foundation_1_1Signal" ],
        [ "StrongId", "classcgs_1_1foundation_1_1StrongId.html", "classcgs_1_1foundation_1_1StrongId" ],
        [ "TlsConfig", "structcgs_1_1foundation_1_1TlsConfig.html", "structcgs_1_1foundation_1_1TlsConfig" ],
        [ "TraceSpan", "structcgs_1_1foundation_1_1TraceSpan.html", "structcgs_1_1foundation_1_1TraceSpan" ],
        [ "Transaction", "classcgs_1_1foundation_1_1Transaction.html", "classcgs_1_1foundation_1_1Transaction" ]
      ] ],
      [ "game", "namespacecgs_1_1game.html", [
        [ "AIBrain", "structcgs_1_1game_1_1AIBrain.html", "structcgs_1_1game_1_1AIBrain" ],
        [ "AISystem", "classcgs_1_1game_1_1AISystem.html", "classcgs_1_1game_1_1AISystem" ],
        [ "AuraHolder", "structcgs_1_1game_1_1AuraHolder.html", "structcgs_1_1game_1_1AuraHolder" ],
        [ "AuraInstance", "structcgs_1_1game_1_1AuraInstance.html", "structcgs_1_1game_1_1AuraInstance" ],
        [ "Blackboard", "classcgs_1_1game_1_1Blackboard.html", "classcgs_1_1game_1_1Blackboard" ],
        [ "BTAction", "classcgs_1_1game_1_1BTAction.html", "classcgs_1_1game_1_1BTAction" ],
        [ "BTCondition", "classcgs_1_1game_1_1BTCondition.html", "classcgs_1_1game_1_1BTCondition" ],
        [ "BTContext", "structcgs_1_1game_1_1BTContext.html", "structcgs_1_1game_1_1BTContext" ],
        [ "BTInverter", "classcgs_1_1game_1_1BTInverter.html", "classcgs_1_1game_1_1BTInverter" ],
        [ "BTNode", "classcgs_1_1game_1_1BTNode.html", "classcgs_1_1game_1_1BTNode" ],
        [ "BTParallel", "classcgs_1_1game_1_1BTParallel.html", "classcgs_1_1game_1_1BTParallel" ],
        [ "BTRepeater", "classcgs_1_1game_1_1BTRepeater.html", "classcgs_1_1game_1_1BTRepeater" ],
        [ "BTSelector", "classcgs_1_1game_1_1BTSelector.html", "classcgs_1_1game_1_1BTSelector" ],
        [ "BTSequence", "classcgs_1_1game_1_1BTSequence.html", "classcgs_1_1game_1_1BTSequence" ],
        [ "CellCoord", "structcgs_1_1game_1_1CellCoord.html", "structcgs_1_1game_1_1CellCoord" ],
        [ "CombatSystem", "classcgs_1_1game_1_1CombatSystem.html", "classcgs_1_1game_1_1CombatSystem" ],
        [ "DamageCalcParams", "structcgs_1_1game_1_1DamageCalcParams.html", "structcgs_1_1game_1_1DamageCalcParams" ],
        [ "DamageEvent", "structcgs_1_1game_1_1DamageEvent.html", "structcgs_1_1game_1_1DamageEvent" ],
        [ "DurabilityEvent", "structcgs_1_1game_1_1DurabilityEvent.html", "structcgs_1_1game_1_1DurabilityEvent" ],
        [ "Enchant", "structcgs_1_1game_1_1Enchant.html", "structcgs_1_1game_1_1Enchant" ],
        [ "Equipment", "structcgs_1_1game_1_1Equipment.html", "structcgs_1_1game_1_1Equipment" ],
        [ "Identity", "structcgs_1_1game_1_1Identity.html", "structcgs_1_1game_1_1Identity" ],
        [ "Inventory", "structcgs_1_1game_1_1Inventory.html", "structcgs_1_1game_1_1Inventory" ],
        [ "InventorySlot", "structcgs_1_1game_1_1InventorySlot.html", "structcgs_1_1game_1_1InventorySlot" ],
        [ "InventorySystem", "classcgs_1_1game_1_1InventorySystem.html", "classcgs_1_1game_1_1InventorySystem" ],
        [ "ItemTemplate", "structcgs_1_1game_1_1ItemTemplate.html", "structcgs_1_1game_1_1ItemTemplate" ],
        [ "MapInstance", "structcgs_1_1game_1_1MapInstance.html", "structcgs_1_1game_1_1MapInstance" ],
        [ "MapMembership", "structcgs_1_1game_1_1MapMembership.html", "structcgs_1_1game_1_1MapMembership" ],
        [ "Movement", "structcgs_1_1game_1_1Movement.html", "structcgs_1_1game_1_1Movement" ],
        [ "ObjectUpdateSystem", "classcgs_1_1game_1_1ObjectUpdateSystem.html", "classcgs_1_1game_1_1ObjectUpdateSystem" ],
        [ "Quaternion", "structcgs_1_1game_1_1Quaternion.html", "structcgs_1_1game_1_1Quaternion" ],
        [ "QuestEntry", "structcgs_1_1game_1_1QuestEntry.html", "structcgs_1_1game_1_1QuestEntry" ],
        [ "QuestEvent", "structcgs_1_1game_1_1QuestEvent.html", "structcgs_1_1game_1_1QuestEvent" ],
        [ "QuestLog", "structcgs_1_1game_1_1QuestLog.html", "structcgs_1_1game_1_1QuestLog" ],
        [ "QuestObjective", "structcgs_1_1game_1_1QuestObjective.html", "structcgs_1_1game_1_1QuestObjective" ],
        [ "QuestReward", "structcgs_1_1game_1_1QuestReward.html", "structcgs_1_1game_1_1QuestReward" ],
        [ "QuestSystem", "classcgs_1_1game_1_1QuestSystem.html", "classcgs_1_1game_1_1QuestSystem" ],
        [ "QuestTemplate", "structcgs_1_1game_1_1QuestTemplate.html", "structcgs_1_1game_1_1QuestTemplate" ],
        [ "SpatialIndex", "classcgs_1_1game_1_1SpatialIndex.html", "classcgs_1_1game_1_1SpatialIndex" ],
        [ "SpellCast", "structcgs_1_1game_1_1SpellCast.html", "structcgs_1_1game_1_1SpellCast" ],
        [ "StatBonuses", "structcgs_1_1game_1_1StatBonuses.html", "structcgs_1_1game_1_1StatBonuses" ],
        [ "Stats", "structcgs_1_1game_1_1Stats.html", "structcgs_1_1game_1_1Stats" ],
        [ "ThreatEntry", "structcgs_1_1game_1_1ThreatEntry.html", "structcgs_1_1game_1_1ThreatEntry" ],
        [ "ThreatList", "structcgs_1_1game_1_1ThreatList.html", "structcgs_1_1game_1_1ThreatList" ],
        [ "Transform", "structcgs_1_1game_1_1Transform.html", "structcgs_1_1game_1_1Transform" ],
        [ "Vector3", "structcgs_1_1game_1_1Vector3.html", "structcgs_1_1game_1_1Vector3" ],
        [ "VisibilityRange", "structcgs_1_1game_1_1VisibilityRange.html", "structcgs_1_1game_1_1VisibilityRange" ],
        [ "WorldSystem", "classcgs_1_1game_1_1WorldSystem.html", "classcgs_1_1game_1_1WorldSystem" ],
        [ "Zone", "structcgs_1_1game_1_1Zone.html", "structcgs_1_1game_1_1Zone" ]
      ] ],
      [ "plugin", "namespacecgs_1_1plugin.html", [
        [ "detail", "namespacecgs_1_1plugin_1_1detail.html", [
          [ "StaticPluginRegistrar", "structcgs_1_1plugin_1_1detail_1_1StaticPluginRegistrar.html", "structcgs_1_1plugin_1_1detail_1_1StaticPluginRegistrar" ]
        ] ],
        [ "CharacterData", "structcgs_1_1plugin_1_1CharacterData.html", "structcgs_1_1plugin_1_1CharacterData" ],
        [ "ChatMessage", "structcgs_1_1plugin_1_1ChatMessage.html", "structcgs_1_1plugin_1_1ChatMessage" ],
        [ "ClassTemplate", "structcgs_1_1plugin_1_1ClassTemplate.html", "structcgs_1_1plugin_1_1ClassTemplate" ],
        [ "DependencySpec", "structcgs_1_1plugin_1_1DependencySpec.html", "structcgs_1_1plugin_1_1DependencySpec" ],
        [ "EventBus", "classcgs_1_1plugin_1_1EventBus.html", "classcgs_1_1plugin_1_1EventBus" ],
        [ "FileWatcher", "classcgs_1_1plugin_1_1FileWatcher.html", "classcgs_1_1plugin_1_1FileWatcher" ],
        [ "GuildData", "structcgs_1_1plugin_1_1GuildData.html", "structcgs_1_1plugin_1_1GuildData" ],
        [ "GuildMember", "structcgs_1_1plugin_1_1GuildMember.html", "structcgs_1_1plugin_1_1GuildMember" ],
        [ "HotReloadManager", "classcgs_1_1plugin_1_1HotReloadManager.html", "classcgs_1_1plugin_1_1HotReloadManager" ],
        [ "IHotReloadable", "classcgs_1_1plugin_1_1IHotReloadable.html", "classcgs_1_1plugin_1_1IHotReloadable" ],
        [ "IPlugin", "classcgs_1_1plugin_1_1IPlugin.html", "classcgs_1_1plugin_1_1IPlugin" ],
        [ "MMORPGPlugin", "classcgs_1_1plugin_1_1MMORPGPlugin.html", "classcgs_1_1plugin_1_1MMORPGPlugin" ],
        [ "PluginActivatedEvent", "structcgs_1_1plugin_1_1PluginActivatedEvent.html", "structcgs_1_1plugin_1_1PluginActivatedEvent" ],
        [ "PluginContext", "structcgs_1_1plugin_1_1PluginContext.html", "structcgs_1_1plugin_1_1PluginContext" ],
        [ "PluginErrorEvent", "structcgs_1_1plugin_1_1PluginErrorEvent.html", "structcgs_1_1plugin_1_1PluginErrorEvent" ],
        [ "PluginInfo", "structcgs_1_1plugin_1_1PluginInfo.html", "structcgs_1_1plugin_1_1PluginInfo" ],
        [ "PluginInitializedEvent", "structcgs_1_1plugin_1_1PluginInitializedEvent.html", "structcgs_1_1plugin_1_1PluginInitializedEvent" ],
        [ "PluginLoadedEvent", "structcgs_1_1plugin_1_1PluginLoadedEvent.html", "structcgs_1_1plugin_1_1PluginLoadedEvent" ],
        [ "PluginManager", "classcgs_1_1plugin_1_1PluginManager.html", "classcgs_1_1plugin_1_1PluginManager" ],
        [ "PluginShutdownEvent", "structcgs_1_1plugin_1_1PluginShutdownEvent.html", "structcgs_1_1plugin_1_1PluginShutdownEvent" ],
        [ "PluginStateSnapshot", "structcgs_1_1plugin_1_1PluginStateSnapshot.html", "structcgs_1_1plugin_1_1PluginStateSnapshot" ],
        [ "StaticPluginEntry", "structcgs_1_1plugin_1_1StaticPluginEntry.html", "structcgs_1_1plugin_1_1StaticPluginEntry" ],
        [ "Version", "structcgs_1_1plugin_1_1Version.html", "structcgs_1_1plugin_1_1Version" ],
        [ "VersionConstraint", "structcgs_1_1plugin_1_1VersionConstraint.html", "structcgs_1_1plugin_1_1VersionConstraint" ]
      ] ],
      [ "service", "namespacecgs_1_1service.html", [
        [ "AuthConfig", "structcgs_1_1service_1_1AuthConfig.html", "structcgs_1_1service_1_1AuthConfig" ],
        [ "AuthServer", "classcgs_1_1service_1_1AuthServer.html", "classcgs_1_1service_1_1AuthServer" ],
        [ "CacheConfig", "structcgs_1_1service_1_1CacheConfig.html", "structcgs_1_1service_1_1CacheConfig" ],
        [ "CircuitBreakerConfig", "structcgs_1_1service_1_1CircuitBreakerConfig.html", "structcgs_1_1service_1_1CircuitBreakerConfig" ],
        [ "ClientSession", "structcgs_1_1service_1_1ClientSession.html", "structcgs_1_1service_1_1ClientSession" ],
        [ "ConnectionPoolManager", "classcgs_1_1service_1_1ConnectionPoolManager.html", "classcgs_1_1service_1_1ConnectionPoolManager" ],
        [ "DBEndpointConfig", "structcgs_1_1service_1_1DBEndpointConfig.html", "structcgs_1_1service_1_1DBEndpointConfig" ],
        [ "DBProxyConfig", "structcgs_1_1service_1_1DBProxyConfig.html", "structcgs_1_1service_1_1DBProxyConfig" ],
        [ "DBProxyServer", "classcgs_1_1service_1_1DBProxyServer.html", "classcgs_1_1service_1_1DBProxyServer" ],
        [ "EloCalculator", "classcgs_1_1service_1_1EloCalculator.html", "classcgs_1_1service_1_1EloCalculator" ],
        [ "GameLoop", "classcgs_1_1service_1_1GameLoop.html", "classcgs_1_1service_1_1GameLoop" ],
        [ "GameServer", "classcgs_1_1service_1_1GameServer.html", "classcgs_1_1service_1_1GameServer" ],
        [ "GameServerConfig", "structcgs_1_1service_1_1GameServerConfig.html", "structcgs_1_1service_1_1GameServerConfig" ],
        [ "GameServerStats", "structcgs_1_1service_1_1GameServerStats.html", "structcgs_1_1service_1_1GameServerStats" ],
        [ "GatewayAction", "structcgs_1_1service_1_1GatewayAction.html", "structcgs_1_1service_1_1GatewayAction" ],
        [ "GatewayConfig", "structcgs_1_1service_1_1GatewayConfig.html", "structcgs_1_1service_1_1GatewayConfig" ],
        [ "GatewayServer", "classcgs_1_1service_1_1GatewayServer.html", "classcgs_1_1service_1_1GatewayServer" ],
        [ "GatewaySessionManager", "classcgs_1_1service_1_1GatewaySessionManager.html", "classcgs_1_1service_1_1GatewaySessionManager" ],
        [ "GatewayStats", "structcgs_1_1service_1_1GatewayStats.html", "structcgs_1_1service_1_1GatewayStats" ],
        [ "GracefulShutdown", "classcgs_1_1service_1_1GracefulShutdown.html", "classcgs_1_1service_1_1GracefulShutdown" ],
        [ "HashedPassword", "structcgs_1_1service_1_1HashedPassword.html", "structcgs_1_1service_1_1HashedPassword" ],
        [ "HealthServer", "classcgs_1_1service_1_1HealthServer.html", "classcgs_1_1service_1_1HealthServer" ],
        [ "HealthServerConfig", "structcgs_1_1service_1_1HealthServerConfig.html", "structcgs_1_1service_1_1HealthServerConfig" ],
        [ "InMemoryTokenStore", "classcgs_1_1service_1_1InMemoryTokenStore.html", "classcgs_1_1service_1_1InMemoryTokenStore" ],
        [ "InMemoryUserRepository", "classcgs_1_1service_1_1InMemoryUserRepository.html", "classcgs_1_1service_1_1InMemoryUserRepository" ],
        [ "InputValidator", "classcgs_1_1service_1_1InputValidator.html", null ],
        [ "ITokenStore", "classcgs_1_1service_1_1ITokenStore.html", "classcgs_1_1service_1_1ITokenStore" ],
        [ "IUserRepository", "classcgs_1_1service_1_1IUserRepository.html", "classcgs_1_1service_1_1IUserRepository" ],
        [ "LobbyConfig", "structcgs_1_1service_1_1LobbyConfig.html", "structcgs_1_1service_1_1LobbyConfig" ],
        [ "LobbyServer", "classcgs_1_1service_1_1LobbyServer.html", "classcgs_1_1service_1_1LobbyServer" ],
        [ "LobbyStats", "structcgs_1_1service_1_1LobbyStats.html", "structcgs_1_1service_1_1LobbyStats" ],
        [ "MapInstanceInfo", "structcgs_1_1service_1_1MapInstanceInfo.html", "structcgs_1_1service_1_1MapInstanceInfo" ],
        [ "MapInstanceManager", "classcgs_1_1service_1_1MapInstanceManager.html", "classcgs_1_1service_1_1MapInstanceManager" ],
        [ "MatchmakingQueue", "classcgs_1_1service_1_1MatchmakingQueue.html", "classcgs_1_1service_1_1MatchmakingQueue" ],
        [ "MatchmakingTicket", "structcgs_1_1service_1_1MatchmakingTicket.html", "structcgs_1_1service_1_1MatchmakingTicket" ],
        [ "MatchResult", "structcgs_1_1service_1_1MatchResult.html", "structcgs_1_1service_1_1MatchResult" ],
        [ "Party", "structcgs_1_1service_1_1Party.html", "structcgs_1_1service_1_1Party" ],
        [ "PartyManager", "classcgs_1_1service_1_1PartyManager.html", "classcgs_1_1service_1_1PartyManager" ],
        [ "PartyMember", "structcgs_1_1service_1_1PartyMember.html", "structcgs_1_1service_1_1PartyMember" ],
        [ "PasswordHasher", "classcgs_1_1service_1_1PasswordHasher.html", "classcgs_1_1service_1_1PasswordHasher" ],
        [ "PersistenceConfig", "structcgs_1_1service_1_1PersistenceConfig.html", "structcgs_1_1service_1_1PersistenceConfig" ],
        [ "PersistenceManager", "classcgs_1_1service_1_1PersistenceManager.html", "classcgs_1_1service_1_1PersistenceManager" ],
        [ "PlayerRating", "structcgs_1_1service_1_1PlayerRating.html", "structcgs_1_1service_1_1PlayerRating" ],
        [ "PlayerSession", "structcgs_1_1service_1_1PlayerSession.html", "structcgs_1_1service_1_1PlayerSession" ],
        [ "PlayerSnapshot", "structcgs_1_1service_1_1PlayerSnapshot.html", "structcgs_1_1service_1_1PlayerSnapshot" ],
        [ "PoolStats", "structcgs_1_1service_1_1PoolStats.html", "structcgs_1_1service_1_1PoolStats" ],
        [ "QueryCache", "classcgs_1_1service_1_1QueryCache.html", "classcgs_1_1service_1_1QueryCache" ],
        [ "QueryStats", "structcgs_1_1service_1_1QueryStats.html", "structcgs_1_1service_1_1QueryStats" ],
        [ "QueueConfig", "structcgs_1_1service_1_1QueueConfig.html", "structcgs_1_1service_1_1QueueConfig" ],
        [ "RateLimiter", "classcgs_1_1service_1_1RateLimiter.html", "classcgs_1_1service_1_1RateLimiter" ],
        [ "RefreshTokenRecord", "structcgs_1_1service_1_1RefreshTokenRecord.html", "structcgs_1_1service_1_1RefreshTokenRecord" ],
        [ "RouteEntry", "structcgs_1_1service_1_1RouteEntry.html", "structcgs_1_1service_1_1RouteEntry" ],
        [ "RouteMatch", "structcgs_1_1service_1_1RouteMatch.html", "structcgs_1_1service_1_1RouteMatch" ],
        [ "RouteTable", "classcgs_1_1service_1_1RouteTable.html", "classcgs_1_1service_1_1RouteTable" ],
        [ "ServiceCircuitBreaker", "classcgs_1_1service_1_1ServiceCircuitBreaker.html", "classcgs_1_1service_1_1ServiceCircuitBreaker" ],
        [ "SignalHandler", "classcgs_1_1service_1_1SignalHandler.html", "classcgs_1_1service_1_1SignalHandler" ],
        [ "Snapshot", "structcgs_1_1service_1_1Snapshot.html", "structcgs_1_1service_1_1Snapshot" ],
        [ "SnapshotConfig", "structcgs_1_1service_1_1SnapshotConfig.html", "structcgs_1_1service_1_1SnapshotConfig" ],
        [ "SnapshotManager", "classcgs_1_1service_1_1SnapshotManager.html", "classcgs_1_1service_1_1SnapshotManager" ],
        [ "TickMetrics", "structcgs_1_1service_1_1TickMetrics.html", "structcgs_1_1service_1_1TickMetrics" ],
        [ "TokenBlacklist", "classcgs_1_1service_1_1TokenBlacklist.html", "classcgs_1_1service_1_1TokenBlacklist" ],
        [ "TokenBucket", "classcgs_1_1service_1_1TokenBucket.html", "classcgs_1_1service_1_1TokenBucket" ],
        [ "TokenClaims", "structcgs_1_1service_1_1TokenClaims.html", "structcgs_1_1service_1_1TokenClaims" ],
        [ "TokenPair", "structcgs_1_1service_1_1TokenPair.html", "structcgs_1_1service_1_1TokenPair" ],
        [ "TokenProvider", "classcgs_1_1service_1_1TokenProvider.html", "classcgs_1_1service_1_1TokenProvider" ],
        [ "UserCredentials", "structcgs_1_1service_1_1UserCredentials.html", "structcgs_1_1service_1_1UserCredentials" ],
        [ "UserRecord", "structcgs_1_1service_1_1UserRecord.html", "structcgs_1_1service_1_1UserRecord" ],
        [ "ValidationResult", "structcgs_1_1service_1_1ValidationResult.html", "structcgs_1_1service_1_1ValidationResult" ],
        [ "WalConfig", "structcgs_1_1service_1_1WalConfig.html", "structcgs_1_1service_1_1WalConfig" ],
        [ "WalEntry", "structcgs_1_1service_1_1WalEntry.html", "structcgs_1_1service_1_1WalEntry" ],
        [ "WriteAheadLog", "classcgs_1_1service_1_1WriteAheadLog.html", "classcgs_1_1service_1_1WriteAheadLog" ]
      ] ],
      [ "Error", "structcgs_1_1Error.html", "structcgs_1_1Error" ],
      [ "Result", "classcgs_1_1Result.html", "classcgs_1_1Result" ],
      [ "Result< void, E >", "classcgs_1_1Result_3_01void_00_01E_01_4.html", "classcgs_1_1Result_3_01void_00_01E_01_4" ],
      [ "Version", "structcgs_1_1Version.html", null ]
    ] ],
    [ "std", null, [
      [ "hash< cgs::ecs::Entity >", "structstd_1_1hash_3_01cgs_1_1ecs_1_1Entity_01_4.html", "structstd_1_1hash_3_01cgs_1_1ecs_1_1Entity_01_4" ],
      [ "hash< cgs::foundation::StrongId< Tag, T > >", "structstd_1_1hash_3_01cgs_1_1foundation_1_1StrongId_3_01Tag_00_01T_01_4_01_4.html", "structstd_1_1hash_3_01cgs_1_1foundation_1_1StrongId_3_01Tag_00_01T_01_4_01_4" ],
      [ "hash< cgs::game::CellCoord >", "structstd_1_1hash_3_01cgs_1_1game_1_1CellCoord_01_4.html", "structstd_1_1hash_3_01cgs_1_1game_1_1CellCoord_01_4" ]
    ] ]
];