var hierarchy =
[
    [ "cgs::game::AIBrain", "structcgs_1_1game_1_1AIBrain.html", null ],
    [ "cgs::game::AuraHolder", "structcgs_1_1game_1_1AuraHolder.html", null ],
    [ "cgs::game::AuraInstance", "structcgs_1_1game_1_1AuraInstance.html", null ],
    [ "cgs::service::AuthConfig", "structcgs_1_1service_1_1AuthConfig.html", null ],
    [ "cgs::service::AuthServer", "classcgs_1_1service_1_1AuthServer.html", null ],
    [ "cgs::foundation::detail::BinaryReader", "structcgs_1_1foundation_1_1detail_1_1BinaryReader.html", null ],
    [ "cgs::game::Blackboard", "classcgs_1_1game_1_1Blackboard.html", null ],
    [ "cgs::game::BTContext", "structcgs_1_1game_1_1BTContext.html", null ],
    [ "cgs::game::BTNode", "classcgs_1_1game_1_1BTNode.html", [
      [ "cgs::game::BTAction", "classcgs_1_1game_1_1BTAction.html", null ],
      [ "cgs::game::BTCondition", "classcgs_1_1game_1_1BTCondition.html", null ],
      [ "cgs::game::BTInverter", "classcgs_1_1game_1_1BTInverter.html", null ],
      [ "cgs::game::BTParallel", "classcgs_1_1game_1_1BTParallel.html", null ],
      [ "cgs::game::BTRepeater", "classcgs_1_1game_1_1BTRepeater.html", null ],
      [ "cgs::game::BTSelector", "classcgs_1_1game_1_1BTSelector.html", null ],
      [ "cgs::game::BTSequence", "classcgs_1_1game_1_1BTSequence.html", null ]
    ] ],
    [ "cgs::service::CacheConfig", "structcgs_1_1service_1_1CacheConfig.html", null ],
    [ "cgs::game::CellCoord", "structcgs_1_1game_1_1CellCoord.html", null ],
    [ "cgs::plugin::CharacterData", "structcgs_1_1plugin_1_1CharacterData.html", null ],
    [ "cgs::plugin::ChatMessage", "structcgs_1_1plugin_1_1ChatMessage.html", null ],
    [ "cgs::service::CircuitBreakerConfig", "structcgs_1_1service_1_1CircuitBreakerConfig.html", null ],
    [ "cgs::plugin::ClassTemplate", "structcgs_1_1plugin_1_1ClassTemplate.html", null ],
    [ "cgs::service::ClientSession", "structcgs_1_1service_1_1ClientSession.html", null ],
    [ "cgs::ecs::ComponentType< T >", "structcgs_1_1ecs_1_1ComponentType.html", null ],
    [ "cgs::foundation::ConfigManager", "classcgs_1_1foundation_1_1ConfigManager.html", null ],
    [ "cgs::service::ConnectionPoolManager", "classcgs_1_1service_1_1ConnectionPoolManager.html", null ],
    [ "cgs::foundation::CorrelationScope", "classcgs_1_1foundation_1_1CorrelationScope.html", null ],
    [ "cgs::game::DamageCalcParams", "structcgs_1_1game_1_1DamageCalcParams.html", null ],
    [ "cgs::game::DamageEvent", "structcgs_1_1game_1_1DamageEvent.html", null ],
    [ "cgs::foundation::DatabaseConfig", "structcgs_1_1foundation_1_1DatabaseConfig.html", null ],
    [ "cgs::service::DBEndpointConfig", "structcgs_1_1service_1_1DBEndpointConfig.html", null ],
    [ "cgs::foundation::DbNull", "structcgs_1_1foundation_1_1DbNull.html", null ],
    [ "cgs::service::DBProxyConfig", "structcgs_1_1service_1_1DBProxyConfig.html", null ],
    [ "cgs::service::DBProxyServer", "classcgs_1_1service_1_1DBProxyServer.html", null ],
    [ "cgs::plugin::PluginManager::DependencyIssue", "structcgs_1_1plugin_1_1PluginManager_1_1DependencyIssue.html", null ],
    [ "cgs::plugin::PluginManager::DependencyReport", "structcgs_1_1plugin_1_1PluginManager_1_1DependencyReport.html", null ],
    [ "cgs::plugin::DependencySpec", "structcgs_1_1plugin_1_1DependencySpec.html", null ],
    [ "cgs::game::DurabilityEvent", "structcgs_1_1game_1_1DurabilityEvent.html", null ],
    [ "cgs::service::EloCalculator", "classcgs_1_1service_1_1EloCalculator.html", null ],
    [ "cgs::game::Enchant", "structcgs_1_1game_1_1Enchant.html", null ],
    [ "cgs::ecs::Entity", "structcgs_1_1ecs_1_1Entity.html", null ],
    [ "cgs::foundation::EntityIdTag", "structcgs_1_1foundation_1_1EntityIdTag.html", null ],
    [ "cgs::ecs::EntityManager", "classcgs_1_1ecs_1_1EntityManager.html", null ],
    [ "cgs::game::Equipment", "structcgs_1_1game_1_1Equipment.html", null ],
    [ "cgs::Error", "structcgs_1_1Error.html", null ],
    [ "cgs::plugin::EventBus", "classcgs_1_1plugin_1_1EventBus.html", null ],
    [ "std::false_type", null, [
      [ "cgs::foundation::detail::is_serializable< T, typename >", "structcgs_1_1foundation_1_1detail_1_1is__serializable.html", null ]
    ] ],
    [ "cgs::foundation::FieldDescriptor< T, M >", "structcgs_1_1foundation_1_1FieldDescriptor.html", null ],
    [ "cgs::plugin::FileWatcher", "classcgs_1_1plugin_1_1FileWatcher.html", null ],
    [ "cgs::foundation::GameDatabase", "classcgs_1_1foundation_1_1GameDatabase.html", null ],
    [ "cgs::foundation::GameError", "classcgs_1_1foundation_1_1GameError.html", null ],
    [ "cgs::foundation::GameJobScheduler", "classcgs_1_1foundation_1_1GameJobScheduler.html", null ],
    [ "cgs::foundation::GameLogger", "classcgs_1_1foundation_1_1GameLogger.html", null ],
    [ "cgs::service::GameLoop", "classcgs_1_1service_1_1GameLoop.html", null ],
    [ "cgs::foundation::GameMetrics", "classcgs_1_1foundation_1_1GameMetrics.html", null ],
    [ "cgs::foundation::GameNetworkManager", "classcgs_1_1foundation_1_1GameNetworkManager.html", null ],
    [ "cgs::foundation::GameSerializer", "classcgs_1_1foundation_1_1GameSerializer.html", null ],
    [ "cgs::service::GameServer", "classcgs_1_1service_1_1GameServer.html", null ],
    [ "cgs::service::GameServerConfig", "structcgs_1_1service_1_1GameServerConfig.html", null ],
    [ "cgs::service::GameServerStats", "structcgs_1_1service_1_1GameServerStats.html", null ],
    [ "cgs::service::GatewayAction", "structcgs_1_1service_1_1GatewayAction.html", null ],
    [ "cgs::service::GatewayConfig", "structcgs_1_1service_1_1GatewayConfig.html", null ],
    [ "cgs::service::GatewayServer", "classcgs_1_1service_1_1GatewayServer.html", null ],
    [ "cgs::service::GatewaySessionManager", "classcgs_1_1service_1_1GatewaySessionManager.html", null ],
    [ "cgs::service::GatewayStats", "structcgs_1_1service_1_1GatewayStats.html", null ],
    [ "cgs::service::GracefulShutdown", "classcgs_1_1service_1_1GracefulShutdown.html", null ],
    [ "cgs::plugin::GuildData", "structcgs_1_1plugin_1_1GuildData.html", null ],
    [ "cgs::plugin::GuildMember", "structcgs_1_1plugin_1_1GuildMember.html", null ],
    [ "std::hash< cgs::ecs::Entity >", "structstd_1_1hash_3_01cgs_1_1ecs_1_1Entity_01_4.html", null ],
    [ "std::hash< cgs::foundation::StrongId< Tag, T > >", "structstd_1_1hash_3_01cgs_1_1foundation_1_1StrongId_3_01Tag_00_01T_01_4_01_4.html", null ],
    [ "std::hash< cgs::game::CellCoord >", "structstd_1_1hash_3_01cgs_1_1game_1_1CellCoord_01_4.html", null ],
    [ "cgs::service::HashedPassword", "structcgs_1_1service_1_1HashedPassword.html", null ],
    [ "cgs::foundation::HealthCheckResult", "structcgs_1_1foundation_1_1HealthCheckResult.html", null ],
    [ "cgs::service::HealthServer", "classcgs_1_1service_1_1HealthServer.html", null ],
    [ "cgs::service::HealthServerConfig", "structcgs_1_1service_1_1HealthServerConfig.html", null ],
    [ "cgs::foundation::HistogramBuckets", "structcgs_1_1foundation_1_1HistogramBuckets.html", null ],
    [ "cgs::plugin::HotReloadManager", "classcgs_1_1plugin_1_1HotReloadManager.html", null ],
    [ "cgs::ecs::IComponentStorage", "classcgs_1_1ecs_1_1IComponentStorage.html", [
      [ "cgs::ecs::ComponentStorage< cgs::game::AIBrain >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::Transform >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::Movement >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::Stats >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::ThreatList >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::SpellCast >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::AuraHolder >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::DamageEvent >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::Inventory >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::Equipment >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::DurabilityEvent >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::QuestLog >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::QuestEvent >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::MapMembership >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::MapInstance >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::VisibilityRange >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::Zone >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< cgs::game::Identity >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ],
      [ "cgs::ecs::ComponentStorage< T >", "classcgs_1_1ecs_1_1ComponentStorage.html", null ]
    ] ],
    [ "cgs::game::Identity", "structcgs_1_1game_1_1Identity.html", null ],
    [ "cgs::plugin::IHotReloadable", "classcgs_1_1plugin_1_1IHotReloadable.html", null ],
    [ "cgs::service::InputValidator", "classcgs_1_1service_1_1InputValidator.html", null ],
    [ "cgs::game::Inventory", "structcgs_1_1game_1_1Inventory.html", null ],
    [ "cgs::game::InventorySlot", "structcgs_1_1game_1_1InventorySlot.html", null ],
    [ "cgs::plugin::IPlugin", "classcgs_1_1plugin_1_1IPlugin.html", [
      [ "cgs::plugin::MMORPGPlugin", "classcgs_1_1plugin_1_1MMORPGPlugin.html", null ]
    ] ],
    [ "cgs::ecs::ISystem", "classcgs_1_1ecs_1_1ISystem.html", [
      [ "cgs::game::AISystem", "classcgs_1_1game_1_1AISystem.html", null ],
      [ "cgs::game::CombatSystem", "classcgs_1_1game_1_1CombatSystem.html", null ],
      [ "cgs::game::InventorySystem", "classcgs_1_1game_1_1InventorySystem.html", null ],
      [ "cgs::game::ObjectUpdateSystem", "classcgs_1_1game_1_1ObjectUpdateSystem.html", null ],
      [ "cgs::game::QuestSystem", "classcgs_1_1game_1_1QuestSystem.html", null ],
      [ "cgs::game::WorldSystem", "classcgs_1_1game_1_1WorldSystem.html", null ]
    ] ],
    [ "cgs::game::ItemTemplate", "structcgs_1_1game_1_1ItemTemplate.html", null ],
    [ "cgs::service::ITokenStore", "classcgs_1_1service_1_1ITokenStore.html", [
      [ "cgs::service::InMemoryTokenStore", "classcgs_1_1service_1_1InMemoryTokenStore.html", null ]
    ] ],
    [ "cgs::service::IUserRepository", "classcgs_1_1service_1_1IUserRepository.html", [
      [ "cgs::service::InMemoryUserRepository", "classcgs_1_1service_1_1InMemoryUserRepository.html", null ]
    ] ],
    [ "cgs::foundation::JsonLogFormatter", "classcgs_1_1foundation_1_1JsonLogFormatter.html", null ],
    [ "cgs::foundation::detail::JsonReader", "structcgs_1_1foundation_1_1detail_1_1JsonReader.html", null ],
    [ "cgs::service::LobbyConfig", "structcgs_1_1service_1_1LobbyConfig.html", null ],
    [ "cgs::service::LobbyServer", "classcgs_1_1service_1_1LobbyServer.html", null ],
    [ "cgs::service::LobbyStats", "structcgs_1_1service_1_1LobbyStats.html", null ],
    [ "cgs::foundation::LogContext", "structcgs_1_1foundation_1_1LogContext.html", null ],
    [ "cgs::game::MapInstance", "structcgs_1_1game_1_1MapInstance.html", null ],
    [ "cgs::service::MapInstanceInfo", "structcgs_1_1service_1_1MapInstanceInfo.html", null ],
    [ "cgs::service::MapInstanceManager", "classcgs_1_1service_1_1MapInstanceManager.html", null ],
    [ "cgs::game::MapMembership", "structcgs_1_1game_1_1MapMembership.html", null ],
    [ "cgs::service::MatchmakingQueue", "classcgs_1_1service_1_1MatchmakingQueue.html", null ],
    [ "cgs::service::MatchmakingTicket", "structcgs_1_1service_1_1MatchmakingTicket.html", null ],
    [ "cgs::service::MatchResult", "structcgs_1_1service_1_1MatchResult.html", null ],
    [ "cgs::game::Movement", "structcgs_1_1game_1_1Movement.html", null ],
    [ "cgs::foundation::NetworkMessage", "structcgs_1_1foundation_1_1NetworkMessage.html", null ],
    [ "cgs::ecs::SystemScheduler::ParallelBatch", "structcgs_1_1ecs_1_1SystemScheduler_1_1ParallelBatch.html", null ],
    [ "cgs::service::Party", "structcgs_1_1service_1_1Party.html", null ],
    [ "cgs::service::PartyManager", "classcgs_1_1service_1_1PartyManager.html", null ],
    [ "cgs::service::PartyMember", "structcgs_1_1service_1_1PartyMember.html", null ],
    [ "cgs::service::PasswordHasher", "classcgs_1_1service_1_1PasswordHasher.html", null ],
    [ "cgs::service::PersistenceConfig", "structcgs_1_1service_1_1PersistenceConfig.html", null ],
    [ "cgs::service::PersistenceManager", "classcgs_1_1service_1_1PersistenceManager.html", null ],
    [ "cgs::foundation::PlayerIdTag", "structcgs_1_1foundation_1_1PlayerIdTag.html", null ],
    [ "cgs::service::PlayerRating", "structcgs_1_1service_1_1PlayerRating.html", null ],
    [ "cgs::service::PlayerSession", "structcgs_1_1service_1_1PlayerSession.html", null ],
    [ "cgs::service::PlayerSnapshot", "structcgs_1_1service_1_1PlayerSnapshot.html", null ],
    [ "cgs::plugin::PluginActivatedEvent", "structcgs_1_1plugin_1_1PluginActivatedEvent.html", null ],
    [ "cgs::plugin::PluginContext", "structcgs_1_1plugin_1_1PluginContext.html", null ],
    [ "cgs::plugin::PluginErrorEvent", "structcgs_1_1plugin_1_1PluginErrorEvent.html", null ],
    [ "cgs::plugin::PluginInfo", "structcgs_1_1plugin_1_1PluginInfo.html", null ],
    [ "cgs::plugin::PluginInitializedEvent", "structcgs_1_1plugin_1_1PluginInitializedEvent.html", null ],
    [ "cgs::plugin::PluginLoadedEvent", "structcgs_1_1plugin_1_1PluginLoadedEvent.html", null ],
    [ "cgs::plugin::PluginManager", "classcgs_1_1plugin_1_1PluginManager.html", null ],
    [ "cgs::plugin::PluginShutdownEvent", "structcgs_1_1plugin_1_1PluginShutdownEvent.html", null ],
    [ "cgs::plugin::PluginStateSnapshot", "structcgs_1_1plugin_1_1PluginStateSnapshot.html", null ],
    [ "cgs::service::PoolStats", "structcgs_1_1service_1_1PoolStats.html", null ],
    [ "cgs::foundation::PreparedStatement", "classcgs_1_1foundation_1_1PreparedStatement.html", null ],
    [ "cgs::game::Quaternion", "structcgs_1_1game_1_1Quaternion.html", null ],
    [ "cgs::ecs::Query< Includes >", "classcgs_1_1ecs_1_1Query.html", null ],
    [ "cgs::service::QueryCache", "classcgs_1_1service_1_1QueryCache.html", null ],
    [ "cgs::service::QueryStats", "structcgs_1_1service_1_1QueryStats.html", null ],
    [ "cgs::game::QuestEntry", "structcgs_1_1game_1_1QuestEntry.html", null ],
    [ "cgs::game::QuestEvent", "structcgs_1_1game_1_1QuestEvent.html", null ],
    [ "cgs::game::QuestLog", "structcgs_1_1game_1_1QuestLog.html", null ],
    [ "cgs::game::QuestObjective", "structcgs_1_1game_1_1QuestObjective.html", null ],
    [ "cgs::game::QuestReward", "structcgs_1_1game_1_1QuestReward.html", null ],
    [ "cgs::game::QuestTemplate", "structcgs_1_1game_1_1QuestTemplate.html", null ],
    [ "cgs::service::QueueConfig", "structcgs_1_1service_1_1QueueConfig.html", null ],
    [ "cgs::service::RateLimiter", "classcgs_1_1service_1_1RateLimiter.html", null ],
    [ "cgs::ecs::Read< Ts >", "structcgs_1_1ecs_1_1Read.html", null ],
    [ "cgs::service::RefreshTokenRecord", "structcgs_1_1service_1_1RefreshTokenRecord.html", null ],
    [ "cgs::Result< T, E >", "classcgs_1_1Result.html", null ],
    [ "cgs::Result< void, E >", "classcgs_1_1Result_3_01void_00_01E_01_4.html", null ],
    [ "cgs::service::RouteEntry", "structcgs_1_1service_1_1RouteEntry.html", null ],
    [ "cgs::service::RouteMatch", "structcgs_1_1service_1_1RouteMatch.html", null ],
    [ "cgs::service::RouteTable", "classcgs_1_1service_1_1RouteTable.html", null ],
    [ "cgs::ecs::ScratchAllocator", "classcgs_1_1ecs_1_1ScratchAllocator.html", null ],
    [ "cgs::foundation::SerializableTraits< T >", "structcgs_1_1foundation_1_1SerializableTraits.html", null ],
    [ "cgs::service::ServiceCircuitBreaker", "classcgs_1_1service_1_1ServiceCircuitBreaker.html", null ],
    [ "cgs::foundation::ServiceLocator", "classcgs_1_1foundation_1_1ServiceLocator.html", null ],
    [ "cgs::foundation::SessionIdTag", "structcgs_1_1foundation_1_1SessionIdTag.html", null ],
    [ "cgs::foundation::SessionInfo", "structcgs_1_1foundation_1_1SessionInfo.html", null ],
    [ "cgs::foundation::Signal< Args >", "classcgs_1_1foundation_1_1Signal.html", null ],
    [ "cgs::foundation::Signal< cgs::foundation::StrongId >", "classcgs_1_1foundation_1_1Signal.html", null ],
    [ "cgs::foundation::Signal< cgs::foundation::StrongId, ErrorCode >", "classcgs_1_1foundation_1_1Signal.html", null ],
    [ "cgs::service::SignalHandler", "classcgs_1_1service_1_1SignalHandler.html", null ],
    [ "cgs::service::Snapshot", "structcgs_1_1service_1_1Snapshot.html", null ],
    [ "cgs::service::SnapshotConfig", "structcgs_1_1service_1_1SnapshotConfig.html", null ],
    [ "cgs::service::SnapshotManager", "classcgs_1_1service_1_1SnapshotManager.html", null ],
    [ "cgs::game::SpatialIndex", "classcgs_1_1game_1_1SpatialIndex.html", null ],
    [ "cgs::game::SpellCast", "structcgs_1_1game_1_1SpellCast.html", null ],
    [ "cgs::game::StatBonuses", "structcgs_1_1game_1_1StatBonuses.html", null ],
    [ "cgs::plugin::StaticPluginEntry", "structcgs_1_1plugin_1_1StaticPluginEntry.html", null ],
    [ "cgs::plugin::detail::StaticPluginRegistrar", "structcgs_1_1plugin_1_1detail_1_1StaticPluginRegistrar.html", null ],
    [ "cgs::game::Stats", "structcgs_1_1game_1_1Stats.html", null ],
    [ "cgs::foundation::StrongId< Tag, T >", "classcgs_1_1foundation_1_1StrongId.html", null ],
    [ "cgs::foundation::StrongId< SessionIdTag >", "classcgs_1_1foundation_1_1StrongId.html", null ],
    [ "cgs::ecs::SystemAccessInfo", "structcgs_1_1ecs_1_1SystemAccessInfo.html", null ],
    [ "cgs::ecs::SystemScheduler", "classcgs_1_1ecs_1_1SystemScheduler.html", null ],
    [ "cgs::ecs::SystemType< T >", "structcgs_1_1ecs_1_1SystemType.html", null ],
    [ "cgs::game::ThreatEntry", "structcgs_1_1game_1_1ThreatEntry.html", null ],
    [ "cgs::game::ThreatList", "structcgs_1_1game_1_1ThreatList.html", null ],
    [ "cgs::service::TickMetrics", "structcgs_1_1service_1_1TickMetrics.html", null ],
    [ "cgs::foundation::TlsConfig", "structcgs_1_1foundation_1_1TlsConfig.html", null ],
    [ "cgs::service::TokenBlacklist", "classcgs_1_1service_1_1TokenBlacklist.html", null ],
    [ "cgs::service::TokenBucket", "classcgs_1_1service_1_1TokenBucket.html", null ],
    [ "cgs::service::TokenClaims", "structcgs_1_1service_1_1TokenClaims.html", null ],
    [ "cgs::service::TokenPair", "structcgs_1_1service_1_1TokenPair.html", null ],
    [ "cgs::service::TokenProvider", "classcgs_1_1service_1_1TokenProvider.html", null ],
    [ "cgs::foundation::TraceSpan", "structcgs_1_1foundation_1_1TraceSpan.html", null ],
    [ "cgs::foundation::Transaction", "classcgs_1_1foundation_1_1Transaction.html", null ],
    [ "cgs::game::Transform", "structcgs_1_1game_1_1Transform.html", null ],
    [ "std::true_type", null, [
      [ "cgs::foundation::detail::is_serializable< T, std::void_t< decltype(SerializableTraits< T >::schema_version)> >", "structcgs_1_1foundation_1_1detail_1_1is__serializable_3_01T_00_01std_1_1void__t_3_01decltype_07Sac1188e26c006f2f00b19e3dfbc7ec84.html", null ]
    ] ],
    [ "cgs::service::UserCredentials", "structcgs_1_1service_1_1UserCredentials.html", null ],
    [ "cgs::service::UserRecord", "structcgs_1_1service_1_1UserRecord.html", null ],
    [ "cgs::service::ValidationResult", "structcgs_1_1service_1_1ValidationResult.html", null ],
    [ "cgs::game::Vector3", "structcgs_1_1game_1_1Vector3.html", null ],
    [ "cgs::plugin::Version", "structcgs_1_1plugin_1_1Version.html", null ],
    [ "cgs::Version", "structcgs_1_1Version.html", null ],
    [ "cgs::plugin::VersionConstraint", "structcgs_1_1plugin_1_1VersionConstraint.html", null ],
    [ "cgs::game::VisibilityRange", "structcgs_1_1game_1_1VisibilityRange.html", null ],
    [ "cgs::service::WalConfig", "structcgs_1_1service_1_1WalConfig.html", null ],
    [ "cgs::service::WalEntry", "structcgs_1_1service_1_1WalEntry.html", null ],
    [ "cgs::ecs::Write< Ts >", "structcgs_1_1ecs_1_1Write.html", null ],
    [ "cgs::service::WriteAheadLog", "classcgs_1_1service_1_1WriteAheadLog.html", null ],
    [ "cgs::game::Zone", "structcgs_1_1game_1_1Zone.html", null ]
];